#!/bin/sh

cd bytecast-common
git pull origin master
cd ..
cd bytecast-fsys
git pull origin master
cd ..
cd bytecast-amd64
git pull origin master
cd ..
cd bytecast-jimple
git pull origin master
cd ..
cd bytecast-runtime
git pull origin master
cd ..
cd bytecast-documents
git pull origin master
cd ..
cd bytecast-test
git pull origin master
cd ..
