#!/bin/sh

cd bytecast-fsys
git pull origin master
cd ..
cd bytecast-amd64
git pull origin master
cd ..
cd bytecast-jimple
git pull origin master
cd ..
cd bytecast-runtime
git pull origin master
cd ..

