#!/bin/sh

git clone git@github.com:dopl/bytecast-common.git
git clone git@github.com:dopl/bytecast-fsys.git
git clone git@github.com:dopl/bytecast-amd64.git
git clone git@github.com:dopl/bytecast-jimple.git
git clone git@github.com:dopl/bytecast-runtime.git
git clone git@github.com:dopl/bytecast-documents.git
